provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  pigo-face-detector:
    lang: go
    handler: ./pigo-openfaas
    image: itbiboo/pigo-openfaas:latest
    environment:
      input_mode: "image"